### ISSUE TITLE
Application crashes if tag is removed prior to successful read

### ISSUE THREAD

**Issue by presto87** [DA-Osborne/Spool-Maker#1]
This application crashes if the NFC tag is removed before the read process is complete.  

I discovered this after I initially didn't realize that the tag had to be left on the scanner after its initial read beep for the read process to complete.

**Comment by DA-Osborne** [comment]
Thanks for discovering this, I believe I have solved the issue and will push the changes in the next few days.

**Comment by DA-Osborne** [comment]
I have pushed the change. If there is still an issue, just reopen and I will have another look.
