### ISSUE TITLE
On Versions of Cura newer than v5.0.0, v5.0.0 is still required

### ISSUE THREAD

**Issue by Monroe07** [DA-Osborne/Spool-Maker#8]
System:
Using Spoolmaker Release v1.1.4.
Using Cura v5.3.0 without v5.0.0 /all prior version removed.

Issue:
Spoolmaker release v1.1.4 will not open unless Cura v5.0.0 is installed in addition to newer versions of Cura being used. Request at minimum that read-me state as such.

**Comment by rachael7** [comment]
Can confirm, Cura 5.3.0 does not register itself the same way in the registry. It wasn't clear to me where 5.3.0 did actually register itself, but I was able to make a temporary workaround by using the Python version of SpoolMaker and hard-coding the install directory in Material.py, All previous versions up to 5.2.1 seem to work though, so if 5.2.1 or earlier is installed, SpoolMaker will take the most recent version before 5.3.0.

**Comment by Maeven-Black** [comment]
I have a clean install of 5.3.1 using install defaults. Looks like Ultimaker changed the location of the registry for this. I made the following change to the CuraMaterial.py file and it ran fine and found/displayed all the installed materials. Obviously not a final solution but at least it runs.

`curaSysDirKey = OpenKey(HKEY_LOCAL_MACHINE, 'SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\App Paths\\UltiMaker Cura 5.3.1-5.3.1\\', 0, KEY_READ)`

ETA:
Just installed 5.4 Beta. Consistent app path as 5.3.1:Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\UltiMaker Cura 5.4.0-beta.1-5.4.0-beta.1

So, this could probably be coded up to parse the 5.3 and 5.4 naming convention.

ETA#2: Below code works to parse the registry for 5.3 and 5.4 and returns the correct installed directory. The parsing code is the same as the existing function but for some reason it fails when calling the function versus putting the code in-line though, so this is what it is for now.

   try:
        # Search for Cura >= v5.3 version
        access_key = OpenKey(HKEY_LOCAL_MACHINE, 'SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\App Paths', 0, KEY_READ)
        curaList = []
        for i in range(0, QueryInfoKey(access_key)[0]):
            curaList.append(EnumKey(access_key, i))
            fList = [k for k in curaList if 'UltiMaker Cura' in k]
            fList.sort()
        curaSysDirKey = OpenKey(HKEY_LOCAL_MACHINE,"SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\App Paths\\" + fList[-1], 0, KEY_READ)
        curaSysDir = os.path.dirname(QueryValueEx(curaSysDirKey, '')[0])
        latestInstalled = 5

Fork created, edits made to CuraMateiral.py, and pull request made.

**Comment by DA-Osborne** [comment]
Thanks for checking into this all! I have merged your changes and recompiled a new version. Please let me know if there are any further issues.
